### ISSUE TITLE
Gif seems to be playing at a lower frame rate

### ISSUE THREAD

**Issue by joao7yt** [XamlAnimatedGif/XamlAnimatedGif#127] opened 2019-04-17 12:34 UTC
- Application type: WPF 4.5+
- Operating system version: Windows 10 Build 17763
- Expected behavior: Gif to play at the normal speed, should be exactly 7 seconds
- Actual behavior: Gif playing around half speed, it's about 13 seconds
- Steps to reproduce the problem:
  1. just run the application with:
```
<Image Width="128" Height="128" gif:AnimationBehavior.SourceUri="/Images/Loading.gif" gif:AnimationBehavior.RepeatBehavior="Forever"/>
```
- If you're having issues with a specific GIF file, please attach or link the file.
![Loading](https://user-images.githubusercontent.com/10665193/56287881-e4980c00-60f3-11e9-8f39-8abc29d05770.gif)

**Comment by thomaslevesque** [comment] 2019-04-17 13:09
Hi @joao7yt,
Thanks for the report. I'm aware of the performance issues, and have some plan to address them as soon as I can find the time (to be honest, I have no idea when that will be). I'm closing this as a duplicate of #88.

**Closed by thomaslevesque** 2019-04-17 13:09 UTC
