### ISSUE TITLE
Performance degrades when displaying more than 30-40 gifs

### ISSUE THREAD

**Issue by jhwheuer** [XamlAnimatedGif/XamlAnimatedGif#86] opened 2016-10-28 14:14 UTC
I love this extension! Love it!
Only I need to disable it in my image grid when there are more then 3 dozen or so animations at the same time. 
A browser does not have issues with that, but my UWP app grinds to almost a standstill...

Anything you can do there?

**Comment by thomaslevesque** [comment] 2016-10-28 14:22
Hi @jhwheuer,

Thanks for the feedback. To be honest, I'm not surprised you're having performance issues; my implementation is nowhere near as optimized as the ones in web browsers..

Unfortunately, I don't think it's possible to improve things significantly without a major rewrite. Someone [suggested](https://github.com/XamlAnimatedGif/XamlAnimatedGif/issues/86) to use the Composition API, but I haven't really looked at yet.

**Comment by jhwheuer** [comment] 2016-10-28 14:45
THANKS for the prompt reply!

Hmmm, any ideas to decorate an image with an indicator that there is an animation present and autostart that animation on hover? Not sure how to do that efficiently in XAML (as that would make the page even more heavy... something like gif:animateOnHover...?

Did not look at the code yet, are you holding the image data permanently in memory or are you accessing disk repeatedly?

**Comment by thomaslevesque** [comment] 2016-10-28 15:00
> Hmmm, any ideas to decorate an image with an indicator that there is an animation present and autostart that animation on hover? Not sure how to do that efficiently in XAML (as that would make the page even more heavy... something like gif:animateOnHover...?

There's nothing built-in to handle this scenario, but it wouldn't be hard to achieve. You could just set `AutoStart` to false, and react to the event in code-behind to start the animation manually.

The `AnimateOnHover` property is an interesting idea, although it's probably too specific. It could be something more generic, e.g. `IsAnimationEnabled`, so that it could be bound to `IsMouseOver` or anything else.

> Did not look at the code yet, are you holding the image data permanently in memory or are you accessing disk repeatedly?

No, it's not held in memory. I access the file or stream repeatedly. The idea was to avoid the memory usage problem I had in WpfAnimatedGif. But now that I think about it, the memory usage problem was mostly caused by the decoded image data of each frame; GIF files are typically not very large, so I could probably hold them in memory, as long as I don't keep the decoded frames. This would avoid a lot of other issues.

**Comment by jhwheuer** [comment] 2016-10-28 15:43
RIght, then I need to read more of your docu, I guess :-P

Anything you could do to make the CPU load lighter would be great. 

Oh, and maybe the time has come to allow XAML to indicate whether Mem or DIsk should be used. You could still treat that as a recommendation and go disk if memory is an issue...  gif:preferRAM or something like that. But thinking about that, that should just be the default behavior anyway. Keep all the anims in memory until that becomes an issue...

Oh, are you animating those images that are not actually visible? That might help, too....

**Comment by jhwheuer** [comment] 2016-10-28 16:17
I am actually banging my head against the limitations of UWP. There is no BitmapImage.isAnimation... property.
Maybe you could here me out here? how do I determine if a downloaded gif actually contains an animation?
Cheers

**Comment by thomaslevesque** [comment] 2016-10-28 19:06
> There is no BitmapImage.isAnimation... property.

Well, that makes sense, since UWP doesn't support animated GIFs (or my library wouldn't need to exist) :wink:

> how do I determine if a downloaded gif actually contains an animation?

No easy way, I'm afraid...

- using `XamlAnimatedGif`: you can assign the file to an `Image` control, and when the `AnimationBehavior.Loaded` event is raised, check the result of `AnimationBehavior.GetAnimator`. If it returns a non-null animator, then it's a GIF image, otherwise it's not. If the `Animator` has a `FrameCount` > 1, then it's an animation.
- using the UWP API, you can load the file with a `BitmapDecoder` and check the `FrameCount`

**Comment by jhwheuer** [comment] 2016-10-28 19:21
THanks. 

Jeesh, developing software for 35 years, and somehow UWP feels like back to hammer and nails...

**Comment by thomaslevesque** [comment] 2017-04-19 18:18
> There is no BitmapImage.isAnimation... property.

> Well, that makes sense, since UWP doesn't support animated GIFs

Actually... there *is* an `IsAnimatedBitmap` property. And also `AutoPlay`, `IsPlaying`, `Play()` and `Stop()`:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage
(see the Animated Images section)
Apparently it's available since build 1607 (Anniversary Update)

**Comment by thomaslevesque** [comment] 2017-04-19 18:40
Just tried it, it works, and probably with much better performance than XamlAnimatedGif.
Of course, if you still have to support pre-1607 version, that won't help...

**Comment by thomaslevesque** [comment] 2018-09-01 09:56
Closing in favor of #88

**Closed by thomaslevesque** 2018-09-01 09:56 UTC
