### ISSUE TITLE
GIF file sometimes doesnt play

### ISSUE THREAD

**Issue by Thomazv** [XamlAnimatedGif/XamlAnimatedGif#105] opened 2017-06-22 12:07 UTC
sometimes the GIF file doesnt play when other gif files have no problem executing. i have added a image file which shows that i sometimes get strange grey lines? does someone know what this means?

![gif file freeze](https://user-images.githubusercontent.com/29628562/27433267-544224b0-5754-11e7-9089-f90667dca7b6.PNG)

**Comment by thomaslevesque** [comment] 2017-06-22 12:14
Hi @Thomazv,

Looks like a rendering bug, but there's not enough information in your post to help you resolve the problem. Please follow the provided [template](https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/master/.github/ISSUE_TEMPLATE.md) for bug reports.

**Comment by Thomazv** [comment] 2017-06-22 12:25
Application type: WPF 4.5+ 
Operating system version: Windows 10
Expected behavior: GIF should execute every time i open the window it is on. 
Actual behavior: GIF file sometimes freezes and shows strange grey lines. 
Steps to reproduce the problem:
repeatly open a window with a gif file on it(it sometimes is another GIF file in the same image object)

**Comment by thomaslevesque** [comment] 2017-06-22 12:39
Thanks for the details @Thomazv.

1. Does it happen with any GIF file, or only with a specific one? In the latter case, could you please provide the GIF file?
2. Could you show the code you're using to display the GIF?

**Comment by Thomazv** [comment] 2017-06-22 13:08
Hi Thomas,

1. It happens with multiple GIF files and sometimes it shocks and sometimes it shows grey lines.

 2. Here is my code: 

`<Image gif:AnimationBehavior.RepeatBehavior="Forever" Width="121" Height="182" gif:AnimationBehavior.SourceUri="{Binding EnumValue, Converter={StaticResource EnumToStringConverter}}" Style="{DynamicResource ImageStyle}" />`

i also use this style for the image:

```
  <Style x:Key="ImageStyle" TargetType="{x:Type Image}">
    <Setter Property="RenderTransformOrigin" Value="0.5,0.5"/>
    <Setter Property="RenderOptions.BitmapScalingMode" Value="HighQuality"/>
    <Setter Property="Stretch" Value="Fill"/>
  </Style>

```

**Comment by thomaslevesque** [comment] 2017-06-22 13:38
OK, I tried to make an app as close to what you described as possible, but I'm unable to reproduce the problem.

What kind of URI does `EnumToStringConverter` return? File, HTTP, resource? Absolute, relative?

You said:

> repeatly open a window with a gif file on it(it sometimes is another GIF file in the same image object)

Could you elaborate? How are you doing that exactly?

If you could send a minimal repro of the problem, it would be very helpful.

**Comment by Thomazv** [comment] 2017-06-22 14:01
EnumToStringConverter returns the following string: "/ProjectName;component/Resources/file1.gif"

I create the window by a simple click on the button then a count down begins and the window closes when the count down is 0. 
The window is simpely created by a window.Show() and disposed by a window.Close().

The problem is this situation happens in like 1/50 of the time i start the window, so it's really random.

**Comment by thomaslevesque** [comment] 2017-06-22 14:10
Thanks for the details.

> The problem is this situation happens in like 1/50 of the time i start the window, so it's really random.

Ah, this is useful to know. Looks like it might be caused by a race condition somewhere.

Does the library raise the `Error` event when it happens?

**Comment by Thomazv** [comment] 2017-06-22 14:14
When it shows the grey lines, yes the error event is raised.

**Comment by thomaslevesque** [comment] 2017-06-22 14:19
> When it shows the grey lines, yes the error event is raised.

And what is the exception? Type, message, stacktrace...

**Comment by Thomazv** [comment] 2017-06-22 14:22
**Message**
`Exception = {"Object reference not set to an instance of an object."}`

**Stacktrace**
```
   at XamlAnimatedGif.Decompression.LzwDecompressStream.ProcessCode(Int32 code, Byte[] buffer, Int32 offset, Int32 count, Int32& read)
   at XamlAnimatedGif.Decompression.LzwDecompressStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at XamlAnimatedGif.Animator.<RenderFrameAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<Play>d__17.MoveNext()
```

**Comment by thomaslevesque** [comment] 2017-06-22 14:24
Thanks, that's very helpful!

**Comment by Thomazv** [comment] 2017-06-22 14:38
np, hope to hear more details soon.

**Comment by thomaslevesque** [comment] 2017-06-22 14:46
OK, I'm still unable to repro. Maybe your GIFs have something special that mine don't have. Could you please share one of the GIF files that exhibit the problem?

**Comment by Thomazv** [comment] 2017-06-22 15:00
I cant share the GIF file but i can tell you that we created the GIF with 150 PNG files at 25 frames per second  if i'm correct.

**Comment by Thomazv** [comment] 2017-06-22 15:03
Could you tell me in what situation(s) this exception could occur?

**Comment by thomaslevesque** [comment] 2017-06-22 15:09
> I cant share the GIF file

That's unfortunate, because it would go a long way toward solving the issue. Based on the stack trace, the problem occurs in the LZW decoding. At some point there was a bug in there that only occurred for images that had certain characteristics. If this is the same situation, I won't be able to fix it without a sample image.

> Could you tell me in what situation(s) this exception could occur?

Well, if I knew, I would be able to fix it...

**Comment by Thomazv** [comment] 2017-06-22 15:12
I will try to change the GIF file/try different GIF files, and see if this makes any differents, i will post my conclusion here. Thanks for the feedback Thomas.

**Comment by Thomazv** [comment] 2017-06-23 07:52
I tested it and other GIF files did not crash in any way, the only differents is that the GIF that did crash and show grey lines, was that they had 128 colors instead of 256.

**Comment by Thomazv** [comment] 2017-06-23 14:42
Hi, 

so i tested some other gif files and i got the following exception with this GIF file:
[http://imgur.com/HCzccUJ](http://imgur.com/HCzccUJ)

(ps: gif file has transparant background)


`Message = "Attempted to read past the end of the stream."`

```
   at XamlAnimatedGif.Animator.<RenderFrameAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<Play>d__17.MoveNext()
```

**Comment by thomaslevesque** [comment] 2017-06-23 14:48
Hi @Thomazv,

Apparently this is a different issue; thanks for providing a sample image. I'll look into it as soon as I can, hopefully during the weekend.

Transparent background shouldn't be an issue, it doesn't really change how the image is encoded.

**Comment by Thomazv** [comment] 2017-06-23 14:50
Hi @thomaslevesque,

Thanks for the fast response, hope to hear more details soon :).

**Comment by thomaslevesque** [comment] 2017-06-24 18:59
@Thomazv when you got the "Attempted to read past the end of the stream." error, did you use the same code as before? Or did you use `StreamSource` instead of `UriSource`? Does the error happen every time for this image?

I might have a fix for this specific error (not for the first one), but I'm unable to reproduce the issue, so I can't test it... If you're able to build the project from source, it would be helpful if you could test it. Does it work if you replace [these 3 lines](https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/29b503497aa3acdd74d41889c7b305df208d7c69/XamlAnimatedGif.Shared/Animator.cs#L335-L337) with this?

    indexStream.ReadAll(indexBuffer, 0, desc.Width);

**Comment by Thomazv** [comment] 2017-06-25 12:29
@thomaslevesque i always used the same code which is UriSource. This error doenst happen every time for this image. when i run the application in debug or release and i start the window on which the gif file is. It sometimes crashes but it works like 75% of the time. 

i will try to run the project from source and replace these lines. Will let you know as soon as posibble.

**Comment by Thomazv** [comment] 2017-06-27 07:35
@thomaslevesque I changed the source and used that dll in my project, i now dont get any more exceptions.

**Comment by thomaslevesque** [comment] 2017-06-27 07:50
> @thomaslevesque I changed the source and used that dll in my project, i now dont get any more exceptions.

Weird... looks like you've found a "heisenbug" :wink:

Did you build in Debug or Release mode?

**Comment by thomaslevesque** [comment] 2017-06-27 07:53
Sorry, I misread your message, I thought you had just built the current source. So the change fixes "Attempted to read past the end of the stream." problem. But the original problem you reported was different; are you saying it no longer happen?

I'll commit the `indexStream.ReadAll`, which is more correct anyway.

**Comment by Thomazv** [comment] 2017-06-27 08:03
I did build in debug and release mode and i'm not getting any exception so far. Will continue testing just to be sure.

**Comment by Thomazv** [comment] 2017-06-27 08:09
@thomaslevesque Thanks for all your help, will wait for your commit =].

**Closed** 2017-06-27 08:26 UTC

**Comment by thomaslevesque** [comment] 2017-06-27 08:38
The "end of the stream" bug is fixed in 1.1.10, which I just released. Thanks for the report @Thomazv!

I closed the issue for now; if you see the original bug again (`NullReferenceException` in `LzwDecompressStream`), don't hesitate to reopen.

**Comment by Thomazv** [comment] 2017-06-27 11:29
@thomaslevesque Thanks, i updated the nuget package. =]

**Comment by Thomazv** [comment] 2017-06-28 08:14
@thomaslevesque I'm afraid that the following day testing i did get the following exception:

`Object reference not set to an instance of an object. `

```
at XamlAnimatedGif.Decompression.LzwDecompressStream.Sequence.Append(Byte b)
   at XamlAnimatedGif.Decompression.LzwDecompressStream.ProcessCode(Int32 code, Byte[] buffer, Int32 offset, Int32 count, Int32& read)
   at XamlAnimatedGif.Decompression.LzwDecompressStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at XamlAnimatedGif.Extensions.StreamExtensions.ReadAll(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at XamlAnimatedGif.Animator.<RenderFrameAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<Play>d__17.MoveNext()
```

**Comment by Thomazv** [comment] 2017-06-28 08:31
I also got another exception once: 

`Exception = {"Attempted to read past the end of the stream."}`

```
at XamlAnimatedGif.Extensions.StreamExtensions.ReadAll(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at XamlAnimatedGif.Animator.<RenderFrameAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<RunAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XamlAnimatedGif.Animator.<Play>d__17.MoveNext()

```

**Comment by thomaslevesque** [comment] 2017-06-28 08:47
Hi @Thomazv,

> I'm afraid that the following day testing i did get the following exception:
> 
>     Object reference not set to an instance of an object.

Looks similar to the initial exception, but not in the same method... It still doesn't happen in an image you can share?

> I also got another exception once:
> 
> Exception = {"Attempted to read past the end of the stream."}

Interesting... So it means the "false" `EndOfStreamException` I "fixed" in 1.1.10 maybe wasn't false after all, the end of the stream was really reached.

Both issues are quite serious, but I'm completely unable to reproduce them... I really need a sample image that exhibits the issue.

**Comment by Thomazv** [comment] 2017-06-28 09:03
@thomaslevesque i just tested it with the following gif file: 

http://imgur.com/HCzccUJ

and got the `object reference not set to an instance of a object` exception.

**Comment by Thomazv** [comment] 2017-06-28 09:10
some more info about how i use the gif files: 

The exception will continue to be thrown when i close and reopen the window on which the gif file is displayed. (so it looks like it has something to do with the resource file it self?)

when i restart my application in debug(or release) the gif file works fine again.

**Comment by thomaslevesque** [comment] 2017-06-28 09:22
Thanks! I'll have a look ASAP (probably not today, though)

**Comment by thomaslevesque** [comment] 2017-06-28 09:23
Ah, it's the same image as before... I tried it dozens of times, and never saw any exception. Does it happen only on your machine, or also on others?

**Comment by thomaslevesque** [comment] 2017-06-28 09:32
It's really strange... In `Sequence.Append`, the only thing that could be null is the `Bytes` property. But it's only null for `ClearCode` and `StopCode`, and `Append` is never called for these sequences. So it shouldn't be possible to have a `NullReferenceException` here... The only explanation I can think of is memory corruption, but it also seems unlikely.

**Comment by Thomazv** [comment] 2017-06-28 09:33
@thomaslevesque i will suggest to my co-worker that we test it on multiple machines to see if it happens on multiple machines. 

I also can share one of the gif files we work with but i can only send it in private because it is commercially used and it cannot be shared.

**Comment by thomaslevesque** [comment] 2017-06-28 09:35
@Thomazv, thanks. You can send it to me at _thomas dot levesque at gmail dot com_.

**Comment by Thomazv** [comment] 2017-06-28 09:52
@thomaslevesque i have send it by email.

**Comment by thomaslevesque** [comment] 2017-06-28 21:31
OK, even with this image, I'm unable to reproduce the problem. I never see any exception being thrown.

What really puzzles me is that the problem seems to be non-deterministic. If it's a bug in the LZW decoding, it should fail every time, but it doesn't. I can see only two possible causes for this non-deterministic behavior:
- concurrency issue, e.g. two or more threads sharing access to the same stream, interfering with each other
- memory corruption

As mentioned above, memory corruption seems unlikely. As for a concurrency issue, I don't see how it could happen; since you're loading the image from a URI, you get a fresh stream every time, so there are never multiple threads accessing it at the same time.

> I will try to reproduce the problem in a test project.

Have you been able to do this? Maybe it's related to something in your code.

**Comment by Thomazv** [comment] 2017-06-29 07:25
@thomaslevesque  i did test it in other test projects and got no exceptions, we will test it on multiple machines here and if the exceptions will occur, i will review them with my colleagues. Will update this post when we have a conclusion.
