### ISSUE TITLE
Free the memory/ processor if the Image is removed from it's parent. (or notify some how that the deletion will happen)

### ISSUE THREAD

**Issue by MugurelGiurcanu** [XamlAnimatedGif/XamlAnimatedGif#27] opened 2015-09-03 09:17 UTC
In case that the image is removed from it's parent, animation control is not reacting. Also there is no possibility to delete the animation control in case that I know when an image will not be used any more. This cause memory leaks and/or the processor is used for useless operations. 

BY EXAMPLE. Consider that i have an chat app and the animated gifs are emoticons. If the application remains opened for a week (this could be an real case), the chat is overloaded. Practically I delete the very very old line manually, but the animation  control are still active and animate an image that is not displayed. If there is, already,  an possibility to control that the perfect, just tell which is it. If not, It will be a big plus to have this feature. 

thanks

**Comment by thomaslevesque** [comment] 2015-09-03 10:13
Good point; I'll see what can be done to improve this.

In the meanwhile, you can just clear the `AnimationBehavior.SourceUri` from the image before you remove it.

**Comment by DarkAngelFR** [comment] 2015-10-18 09:25
Hello,
  I've been using the control to show a GIF in a "popup" control that is shown when calling server (rest service). This popup is shown between pages of the app.
  If you navigate a lot, the CPU is overloaded and handles goes up due to the component not properly closing (found it using VS diagnostics tool). Clearing the navigation stack and looking at GC collect does'nt help. The app is becoming unusable quickly - images not properly loading, key press being taken into account slowly, ...
  After removing the control the app is working ok (no CPU overload, no handles staying opens, ...). The issue was disturbing on W8 app, with W10 UWP it's just not possible...

  Tried setting the SourceUri to null on popup closure but not better :(

  Any idea?

**Comment by thomaslevesque** [comment] 2015-10-18 12:54
Setting SourceUri to null *should* work... maybe I should requalify this as a bug. Could you post a small project that reproduces the issue to help investigate ?

**Comment by DarkAngelFR** [comment] 2015-10-18 19:04
Hello,
Thanks for quick response, I will do a small project to reproduce (my guess is that it comes from popup stuff). Do you mind if some comments are in French? ;-)
Will send you the zip tomorrow morning (french time).
Regards.

**Comment by thomaslevesque** [comment] 2015-10-18 19:33
> Do you mind if some comments are in French? ;-)

Pas de problème, je devrais pouvoir m'en sortir ;)

**Comment by DarkAngelFR** [comment] 2015-10-19 06:15
Hello,
  To make this easier, my message will be in French. To english people : it's just a sample that shows the issue using the control in a Popup. I suppose Thomas (or myself) will give the solution (I hope) in English.

Bonjour,
  Je me doutais que le français ne poserait pas de soucis!
  J'ai mis un petit projet démo sur mon drive : http://1drv.ms/1jwxrIT
  Pour reproduire le bug :
    - Lance et click sur Ecran1 puis Main, puis Ecran1... (en gardant la souris au même endroit ca va vite)

  Ici j'ai un crash de l'application assez rapidement. Si je retire le control et ne laisse que l'image statique : aucun soucis. Tu verras dans la PopupLoading (xaml et CS) ce que j'ai tenté de faire (set de la source uniquement à l'affichage, set à null, ...). Je te laisse voir mes commentaires dans le code.

  Remarque : tu verras que j'utilise la popup entre écran 1 et écran 2, mais pas entre Main et Ecran1 : pas besoin d'afficher le control pour que ca plante! (je suppose que le constructeur de la popup suffit à "construire" le XamlAnimatedGif qui ne se décharge pas bien).
  Si tu as une solution (même pas propre), je suis prenneur!! On est en test final ces 2 prochaines semaines (avec user et tout), on test mi Novembre sur site (l'application finale est une sorte de SelfService en carrière de gravier pour laisser les chauffeurs s'enregistrer en autonome avec relevé de poids et tout) et production prévu début décembre (sous windows 10, cible environs 50 usines) : si d'ici la je n'arrive pas a faire marcher ton composant je devrais soit retirer ces sublimes gif animés, soit utiliser un autre composant.

  Merci pour l'aide,
       Stéphane

Ps: tu peux me contacter par mail : darkangel -at- idlezone.org

**Comment by thomaslevesque** [comment] 2015-10-22 22:51
I think I found where the problem was coming from. Not only the `Animator` wasn't disposed when the image was unloaded, but it was created even if the image was not yet loaded.. I changed the code to defer loading the animation until the `Image` is loaded, this seems to fix the problem. (of course I also added code to dispose the `Animator` when the image is unloaded)

@DarkAngelFR, could you please test [branch issue27 from my repo](https://github.com/thomaslevesque/XamlAnimatedGif/tree/issue27) ? If it works for you I'll merge it and issue a new release.

**Comment by DarkAngelFR** [comment] 2015-10-23 05:45
Hello,
  Thanks for quick response! I will get the branch and integrate this build in my project to test, I was using nugget package so will need few time to do this ;-) will try to do this before end of today so if it seems nice I may send it to real life test Monday ^-^

**Comment by DarkAngelFR** [comment] 2015-10-23 13:39
Hello,
  We made tests with demo app and looks like CPU is a lot better, no more memory overload (still a little but hard to say if it's a leak or if it's just waiting for GC to collect), handles looks better also ;-) great fix in few lines of change :+1: 
  We are integrating this in our main application that is being tested by business teams next week. I propose we let them validate the fix so you can rollout the nuget package next week :-)
  Thanks for quick fix!

**Comment by thomaslevesque** [comment] 2015-10-23 14:00
OK, thanks for the feedback

**Comment by DarkAngelFR** [comment] 2015-10-24 09:00
Hello,
  We found an issue due to change made in the activation of animation :(
  In our app, we display a popup "loading" that allow users to see that we are doing something in the background (connecting to remote server, getting truck weights from loading bridges, ...). When an error occurs, we show a message to the user and stay on the current page, when it's ok we navigate to next page.
  With Fix#27 memory and other are great but if an error occur and we re-try to show the popup : the animation does not start anymore.
  I reproduce the issue in my small demo app : remove the line "Frame.Navigate(typeof(Ecran2));" in Ecran1.xaml.cs, launch the app, click on Ecran2 button : this will show the loading popup (perfect with animation), then re-click the button : the popup will be shown but animation not starting...
  Tried debugging your repos version but strange is that in some cases with breakpoints it works : looks like if it runs "normal" something is broken in animation but with some breakpoints sometimes it works ok...
  Tell me if you wants me to test more and/or to check something ;-)
  I can commit to your repos the test app if you wants (I will need to be contributor for this I guess, never checked in on github until now...)

**Comment by thomaslevesque** [comment] 2015-10-24 13:59
OK, I see what's going on. In the Loaded event handler, I unsubscribed from the Loaded event, because I didn't consider that an unloaded control could be loaded again later. I changed the code to re-subscribe to Loaded when the image is unloaded. I fixed the code in my branch, let me know if it works for you.

> I can commit to your repos the test app if you wants (I will need to be contributor for this I guess, never checked in on github until now...)

No, that's not how it works ;)
You never push anything to someone else's repository; if you want to contribute code to a project, you fork it, make your changes on a branch in your fork, and make a pull request to integrate your branch.
But anyway, your test project has nothing to do in my repo, since it's not part of my project. If you just want to share it, create a repo and put it there.

**Comment by DarkAngelFR** [comment] 2015-10-25 09:07
Hello,
  I checked with latest change and looks better. I have been able to make testing app crash but was when stress testing it, maybe was too fast in switch from load/unload events and that for sure won't happens in real life. We will bring this version to end-users tomorrow for double check :)
  About contribute : I was thinking of proposing changes but as in the original branch the fix27 is not there I had to check in your repos, now I understand better how it should be done ;)
  You are true, my test project don't have to be in your project, my goal was more to had another sample : you testapp winrt and wpf, I was thinking on providing a UWP sample (using same philosophy as yours, adding popup sample in it). May publish it in my own repos later :-)

  Again thanks for quick fix, will validate middle of next week!

**Comment by DarkAngelFR** [comment] 2015-10-30 10:27
Hello,
  Just a quick message to confirm you that it works like a charm.
  Thanks for the fix, will wait for nuget update to remove our own build in next release ;)

**Comment by thomaslevesque** [comment] 2015-10-30 10:48
OK, thanks for confirming! I will merge the fix and update the NuGet package now.

**Closed** 2015-10-30 12:52 UTC
Labels: enhancement

**Comment by thomaslevesque** [comment] 2015-10-30 12:56
The fix is available on NuGet
