### ISSUE TITLE
UI freeze when switching image when built to .NET Native

### ISSUE THREAD

**Issue by nikbondarenko** [XamlAnimatedGif/XamlAnimatedGif#59] opened 2016-02-22 16:50 UTC
Hi!
When I try set new source to your behavior it throw many TaskCanceledException, OperationCanceledException exceptions (in Output) and it freeze UI. It trow exceptions because cancellation token trow exception when cancelled..
Would you please fix it because I like your nuget but is freeze UI when I re-set source.
Regards

**Comment by thomaslevesque** [comment] 2016-02-22 17:12
Hi,

The fact that it throws cancellation exceptions is by design; these exceptions are caught, what you're seeing in Output are the "first chance exceptions" (this is when the debugger is notified that an exception is thrown, even before the exception has been caught). This is probably not what is causing the freeze.

I'll need more information to be able to help you:
- what type of application is it? (WPF, UWP, Windows 8, Windows Phone, Silverlight...)
- what code do you use to set or reset the source?
- if you pause the debugger when the app freezes, where is the UI thread blocked?

If you could provide a minimal repro of the issue, it would also help a lot.

**Comment by nikbondarenko** [comment] 2016-02-23 08:25
Hi,
I created sample for you. I insert your code in project (remove directives for more clean view). You can find it in folder "XamlAnimatedGif".  
Specific - it isn't freeze UI when you are working in Debug mode. But when i enable debuging in .Net Native - it freeze when I am changing source. 
I create new mode - "Debug .Net Native" for you for more clean view of the problem. 
You can find project [here](1drv.ms/1RYo1DN). 
I use UWP platform (Windows 10).


Regards, Nikita.

**Comment by thomaslevesque** [comment] 2016-02-23 11:15
Thanks for the sample @nikbondarenko.

I haven't done anything to support .NET native, so I can't make any guarantee about how it will work... Actually, the lib doesn't even explicitly support UWP; it was initially built for WinRT (Windows 8), and just happened to work on UWP without modification.

I'll look at your project later today and try to understand what's going on.

**Comment by nikbondarenko** [comment] 2016-02-23 11:26
Thanks, @thomaslevesque 
I will wait for your fix this freezing because I love this library and I want further use it! :)

Regards, Nikita

**Comment by thomaslevesque** [comment] 2016-02-23 21:42
There seems to be a problem with OneDrive right now, I can't download the file...

**Comment by thomaslevesque** [comment] 2016-02-23 21:46
OK, managed to get it anyway... direct download is broken, but I was able to copy it to my own OneDrive, and the synchronization pulled it down)

**Comment by thomaslevesque** [comment] 2016-02-23 22:35
OK, I'm not sure what's going on... The problem seems to occur only when built for .NET Native, otherwise it works fine. And since I don't know anything about .NET Native, it's pretty hard to find the root cause...

**Comment by thomaslevesque** [comment] 2016-02-23 23:27
I just realized the problem occurs *only* when the debugger is attached. It's not the app or the library that causes the freeze, it's the debugger! If you run without debugging (Ctrl+F5), the app doesn't freeze, even with .NET Native enabled.

I realize it's still annoying when you're debugging, but since it won't happen in the deployed app, it's not a very serious issue. And anyway, if it's a bug, it's a bug in the debugger, not in the library, so I'm closing the issue for now.

**Closed** 2016-02-23 23:28 UTC
Labels: question
