### ISSUE TITLE
File remains locked after loading a non-GIF image

### ISSUE THREAD

**Issue by coczero** [XamlAnimatedGif/XamlAnimatedGif#66] opened 2016-04-18 20:56 UTC
With WPFAnimatedGif it was possible to display other supported formats than .gif. 
Is this also possible with this new library?

**Comment by thomaslevesque** [comment] 2016-04-18 20:58
Yes, it's possible. If the image is not a GIF, it will be displayed as a static image.

**Comment by coczero** [comment] 2016-04-19 16:46
Hi, thanks for the info.
I have another question.
Is it possible to load a gif in a way I can still do file operations on it?
I tried to load a dummy image before doing something to the file, but it still seems to be open if it happens too fast.

**Comment by thomaslevesque** [comment] 2016-04-19 18:05
You can unload the image by setting the `SourceUri` to null. It should dispose the file stream (i.e. close the file).

**Comment by coczero** [comment] 2016-04-19 18:25
Sadly this doesn't do it for me.
If I set the source uri to null right before I try to the delete the image I still get the message that the file is opened by my app. I also tried it with your example WPF app, just added a button which deletes the SelectedImage, same result

**Comment by thomaslevesque** [comment] 2016-04-19 18:37
> I also tried it with your example WPF app, just added a button which deletes the SelectedImage, same result

Strange... I just did the same test, and the file was correctly closed (I was able to delete it). Are you sure your app isn't opening the file somewhere else? How are you loading the image? Are you using `SourceUri` or `SourceStream`?

**Comment by coczero** [comment] 2016-04-19 18:41
I am binding the SourceUri to an Uri Property. 

Just for the information, this is how I changed your WPF example: (I just changed the GC button event)
`        private void btnGC_Click(object sender, RoutedEventArgs e)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();

	    string bla = SelectedImage;
	    SelectedImage = null;
	    File.Delete(bla);
        }`

**Comment by thomaslevesque** [comment] 2016-04-19 19:00
I just did this (in a new button):

            string current = SelectedImage;
            if (string.IsNullOrEmpty(current))
                return;
            SelectedImage = null;
            File.Delete(current);

The file was correctly deleted. Not sure what's going on... I don't see any reason why it works for me and not for you. Can you put a breakpoint in `Animator.Dispose` and make sure it's called before `File.Delete`?

**Comment by coczero** [comment] 2016-04-19 19:04
Unfortunately, the breakpoint is neither hit before File.Delete, nor is it hit when I comment out the File.Delete call (but I still call SelectedImage = null)

**Comment by thomaslevesque** [comment] 2016-04-19 19:11
> Unfortunately, the breakpoint is neither hit before File.Delete, nor is it hit when I comment out the File.Delete call (but I still call SelectedImage = null)

OK, we're getting closer... Could you set a breakpoint in `AnimationBehavior.InitAnimation` and execute step by step from there? It should call `ClearAnimatorCore`, which in turns disposes the `Animator`. I'd check this myself, but since I can't reproduce the issue on my machine, it wouldn't be very useful...

**Comment by coczero** [comment] 2016-04-19 19:16
I see the problem now...
I test mostly with non-gif images, in whose cases the Animator.Dispose doesn't get called because

> var animator = GetAnimator(image);
>             if (animator == null)
>                 return;

I tried again with some gif images and all of them seem to be deleting fine. Probably missed those because I mainly test with .pngs and .bmps.
So there's just the question left how to Dispose other imgs than gif so one can delete them :)

**Comment by thomaslevesque** [comment] 2016-04-19 19:22
Ah, I see. This line is probably the culprit:

    image.Source = new BitmapImage(sourceUri);

When used this way, `BitmapImage` keeps the file locked, and there's no way to explicitly dispose it.

Congrats, you found a bug :wink:

**Comment by coczero** [comment] 2016-04-19 19:25
Great! :) 
Glad to hear that.
I am really dependent on your awesome library =D
I used WpfAnimatedGif prior to this but I had problems with it's memory management.
Yesterday I saw that you rewrote the lib. And the memory usage is really good.
Really grateful for this and I hope you can fix that bug soon :)

**Comment by thomaslevesque** [comment] 2016-04-19 19:31
> And the memory usage is really good.

Indeed, that was one of the main reasons for the rewrite. It does use more CPU, though... nothing's free :wink:

The bug should be easy enough to fix.

**Comment by thomaslevesque** [comment] 2016-04-19 20:02
Should be fixed now. Would you mind testing the new package from [this feed](https://ci.appveyor.com/nuget/xamlanimatedgif-c9wa78amsykc) before I merge and publish to NuGet?

**Comment by coczero** [comment] 2016-04-19 20:14
Just tested it, looks fine :)
Thanks for the quick fix!

**Closed** 2016-04-19 20:20 UTC
Labels: bug

**Comment by thomaslevesque** [comment] 2016-04-19 20:25
Merged and deployed to NuGet.

Thanks for the bug report!
